name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install test suite and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage==6.4.4 pytest==7.1.3
      - name: Test with pytest
        run: |
          coverage run -m pytest test
          coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2